name: CI
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm run build
      - run: npm run type-check
      - run: npm run coverage

      - name: Converts Markdown to HTML
        uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: coverage/index.html
          github-corners: https://github.com/jaywcjlove/rehype-ignore
      
      - name: Create Coverage Badges
        uses: jaywcjlove/coverage-badges-cli@main

      - name: Generate Contributors Images
        uses: jaywcjlove/github-action-contributors@main
        with:
          filter-author: (renovate\[bot\]|renovate-bot|dependabot\[bot\])
          output: coverage/CONTRIBUTORS.svg
          avatarSize: 42